### ISSUE TITLE
Update QMO blog to reflect current reality

### ISSUE THREAD

**Issue by stephendonner** [mozilla/quality.mozilla.org#16]
We @mozilla/firefox-test-engineering (and perhaps other individuals?) should figure out a plan to update this blog to reality.

A good start would be to look through the team-specific additions from the QMO6 landing, and figure out what to do with them (likely remove them):

https://github.com/mozilla/quality.mozilla.org/commit/956db2f12b5f778b26c511f17564c812a7ac0b36

**Comment by rbillings** [comment]
What does 'update this blog to reality' mean? That PR was from years back, and it looks like the site and the blog are actively used by other teams- so I'm convinced we need to do anything for it.
